version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: chatop_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: chatop_db
      MYSQL_USER: chatop_user
      MYSQL_PASSWORD: chatop_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chatop_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
volumes:
  mysql_data:
