spring:
  application:
    name: ChaTop

  datasource:
    url:      ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8081}

springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    persist-authorization: true
    display-request-duration: true
