# src/main/resources/application.yml

spring:
  application:
    name: ChaTop

  datasource:
    url: jdbc:mysql://localhost:3306/chatop_db
    username: chatop_user
    password: chatop_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    persist-authorization: true
    display-request-duration: true
